spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      value-deserializer: ${SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER:org.apache.kafka.common.serialization.ByteArrayDeserializer}
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
  mail:
    default-encoding: UTF-8
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    port: ${SPRING_MAIL_PORT:587}
    protocol: ${SPRING_MAIL_PROTOCOL:smtp}
    test-connection: ${SPRING_MAIL_TEST_CONNECTION:false}
    properties:
      mail.smtp.ssl.trust: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST:*}
      mail.smtp.auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
      mail.smtp.starttls.enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}
  data:
    redis:
      port: 6379
      host: localhost
server:
  port: ${SERVER_PORT:8088}
