spring:
  application:
    name: identity-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_1},${KAFKA_2},${KAFKA_3}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        partitioner.class: org.apache.kafka.clients.producer.internals.DefaultPartitioner
        linger.ms: 100  # Điều chỉnh thời gian chờ đợi để tối ưu hóa batching
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
jwt:
  signer-key: HJ4ppveef04BKJzTq+dyLhRdicqYiQWxaSqTLiTUxksDu4zMs/NLfrJsbHz+4OiB
  expiration-duration: 3600 # in sec
  refreshable-duration: 3600 # in sec
app:
  services:
    profile: ${PROFILE_URL}
outbound:
  identity:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    redirect-uri: ${REDIRECT_URI}
server:
  port: 8080
application:
  api:
    prefix: /identity
