spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8089
  servlet:
    context-path: /post
