spring:
  application:
    name: post-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

server:
  port: 8080
application:
  api:
    prefix: /post
