server:
  port: 8080
application:
  api:
    prefix: /search
spring:
  application:
    name: search-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
elasticsearch:
  host_and_port: ${ELASTICSEARCH_HOST_AND_PORT}
  URL: ${ELASTICSEARCH_URL}

